on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t helmolabo9.azurecr.io/helmolabo9:${{ github.sha }}
      
    - uses: Azure/container-scan@v0
      with:
        image-name: helmolabo9.azurecr.ioo/helmolabo9:${{ github.sha }}
    
    - uses: Azure/docker-login@v1
      with:
        login-server: contoso.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: docker push helmolabo9.azurecr.io/helmolabo9:${{ github.sha }}
